### ISSUE TITLE
Not able to connect

### ISSUE THREAD

**Issue by houshuang** [dvargas92495/roamjs-multiplayer#1]
Trying to set up two synchronous graphs, get this message on both 
![image](https://user-images.githubusercontent.com/61575/155320100-e0ddc202-7c1e-4ad3-ac5e-705b332b9f70.png)

**Comment by dvargasfuertes** [comment]
There could be any host of user errors leading to this, including using the "Setup Multiplayer" command for both graphs instead of Setup for one and Connect for the other.

I still need to flesh out the documentation for this extension. Once I do, let's follow up then to see if we're still running into issues after following those directions
